name = "slack-status-updater"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[triggers]
crons = ["0 8 * * *"]  # Run every day at 8:00 AM

[vars]
# These will be overridden by actual secret values in the Cloudflare dashboard
GOOGLE_CLIENT_ID = ""
GOOGLE_CLIENT_SECRET = ""
GOOGLE_REFRESH_TOKEN = ""
SLACK_USER_TOKEN = ""
SLACK_BOT_TOKEN = ""
SLACK_USER_ID = "" 